# Generated by Django 5.2.6 on 2025-10-01 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalosaathiapp', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('pickup', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('two-wheeler', 'Two-Wheeler'), ('four-wheeler', 'Four-Wheeler')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('distance_km', models.FloatField()),
                ('cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
