# Generated by Django 5.2.6 on 2025-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalosaathiapp', '0005_ride_pickup_coords_alter_ride_gender_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dest_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='destination_coords',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default-avatar.png', upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
