# Generated by Django 5.2.6 on 2025-10-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalosaathiapp', '0006_ride_dest_distance_ride_destination_coords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
