# Generated by Django 5.2.6 on 2025-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalosaathiapp', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20, null=True),
        ),
    ]
